# -*- coding: utf-8 -*-
"""Interface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S72Z30zr9ASJ1kREP5HaEoDx7b-XCwBr
"""

def management_report() :
  while True:
    print('\n ------------------------- \n')

    print('Select a reporting department, or quit.')
    print(' 0. Quit')
    print(' 1. Marketing')
    print(' 2. Inventory')
    print(' 3. Vendors')
    print('> ', end='')

    choice = input()

    match choice:
      case '0' : break
      case '1' :
        print('Would you like to generate a general report, or input parameters?')
        print( '0. Quit')
        print(' 1. General')
        print(' 2. Input Parameters')

        marketing_choice = input()

        match marketing_choice :
          case '0' : break
          case '1' :
            print('Generating general marketing report...')
            #general_marketing_report(file = 'marketing.md')
            print('Done! File name: marketing.md')
          case '2' :

            # Pick product type
            product_chosen = False
            while product_chosen == False :

              print('Select a product: ')
              print(' 0. Quit')
              print(' 1. DVDs')
              print(' 2. Video Games')

              product_choice = input()

              match product_choice:
                case '0' : break
                case '1' :
                  product = 'DVD'
                  product_chosen = True
                case '2' :
                  product = 'Video Games'
                  product_chosen = True
                case _ : print(f'Error: Unrecognized option: {product_choice}.')

            # Pick region
            region_chosen = False
            while region_chosen == False :
              print('Select a region: ')
              print(' 0. Quit')
              print(' 1. Southern')
              print(' 2. Central')
              print(' 3. West Pacific')
              print(' 4. Atlantic')
              print(' 5. All')

              region_choice = input()

              match region_choice:
                case '0' : break
                case '1' :
                  region = 'SOUTHERN'
                  region_chosen = True
                case '2' :
                  region = 'CENTRAL'
                  region_chosen = True
                case '3' :
                  region = 'WESTPAC'
                  region_chosen = True
                case '4' :
                  region = 'ATLATIC'
                  region_chosen = True
                case '5' :
                  region = '*'
                  region_chosen = True
                case _ : print(f'Error: Unrecognized option: {region_choice}.')

              gender_chosen = False
              while gender_chosen == False :

                print('Select a gender: ')
                print(' 0. Quit')
                print(' 1. Male')
                print(' 2. Female')
                print(' 3. All')

                gender_choice = input()

                match gender_choice :
                  case '0' : break
                  case '1' :
                    gender = 'M'
                    gender_chosen = True
                  case '2' :
                    gender = 'F'
                    gender_chosen = True
                  case '3' :
                    gender = '*'
                    gender_chosen = True
                  case _ : print(f'Error: Unrecognized option: {gender_choice}.')

              age_chosen = False
              while age_chosen == False :

                print('Select a age range: ')
                print(' 1. Under 18')
                print(' 2. 18-24')
                print(' 3. 25-34')
                print(' 4. 35-44')
                print(' 5. 45-54')
                print(' 6. 55-64')
                print(' 7. 65+')

                age_choice = input()

                match age_choice :
                  case '0' : break
                  case '1' :
                    age = 'Under 18'
                    age_chosen = True
                  case '2' :
                    age = '18-24'
                    age_chosen = True
                  case '3' :
                    age = '25-34'
                    age_chosen = True
                  case '4' :
                    age = '35-44'
                    age_chosen = True
                  case '5' :
                    age = '45-54'
                    age_chosen = True
                  case '6' :
                    age = '55-64'
                    age_chosen = True
                  case '7' :
                    age = '65+'
                    age_chosen = True
                  case _ : print(f'Error: Unrecognized option: {age_choice}.')

            print(f'User marketing report: {product}, {region}, {gender}, {age}')
            print('Generating user marketing report...')
            #user_marketing_report(file = 'marketing.md')
            print('Done! File name: marketing.md')

      case '2' :
        print('Generating inventory report...')
        #general_inventory_report(file = 'inventory.md')
        print('Done! File name: inventory.md')
      case '3':
        print('Generating inventory report...')
        #general_vendor_report(file = 'vendor.md')
        print('Done! File name: vendor.md')
      case _ : print(f'Error: Unrecognized option: {choice}.')

management_report()